# Generated by Django 5.2.8 on 2025-11-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('exported_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_minutes', models.PositiveIntegerField(default=60)),
                ('channels', models.CharField(default='email', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cấu hình nhắc nhở',
                'verbose_name_plural': 'Cấu hình nhắc nhở',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('priority', models.CharField(choices=[('Low', 'Thấp'), ('Medium', 'Trung bình'), ('High', 'Cao'), ('Urgent', 'Khẩn cấp')], default='Medium', max_length=10, verbose_name='Mức ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nhắc nhở')),
                ('completed', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('daily_reminder_time', models.TimeField(blank=True, null=True, verbose_name='Giờ nhắc hằng ngày')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todo.category', verbose_name='Danh mục')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Các công việc',
            },
        ),
        migrations.CreateModel(
            name='TaskShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Chỉ xem'), ('edit', 'Được sửa')], default='view', max_length=10)),
                ('share_link', models.CharField(db_index=True, max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_shares_received', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='todo.todo')),
            ],
            options={
                'verbose_name': 'Chia sẻ công việc',
                'verbose_name_plural': 'Chia sẻ công việc',
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('notification_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='todo.notificationsetting')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='todo.todo')),
            ],
            options={
                'verbose_name': 'Thông báo đã gửi',
                'verbose_name_plural': 'Thông báo đã gửi',
            },
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='todo.todo'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='todo.todo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_category_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='sentnotification',
            unique_together={('notification_setting', 'todo')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationsetting',
            unique_together={('owner', 'todo')},
        ),
    ]
