# Generated by Django 5.2.8 on 2025-11-13 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('priority', models.CharField(choices=[('Low', 'Thấp'), ('Medium', 'Trung bình'), ('High', 'Cao'), ('Urgent', 'Khẩn cấp')], default='Medium', max_length=10, verbose_name='Mức ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nhắc nhở')),
                ('completed', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('daily_reminder_time', models.TimeField(blank=True, null=True, verbose_name='Giờ nhắc hằng ngày')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todo.category', verbose_name='Danh mục')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Các công việc',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_category_per_user'),
        ),
    ]
