# Generated by Django 5.2.9 on 2025-12-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_todo_owner_i_b3cdfd_idx',
            old_name='todo_owner_completed_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_todo_owner_i_bc0186_idx',
            old_name='todo_owner_due_at_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_todo_owner_i_1b8216_idx',
            old_name='todo_owner_priority_idx',
        ),
    ]
